config/routes.rb
Rails.application.routes.draw do

  devise_for :users
  resources :product_categories

  resources :products

  root to: "products#index"

  resources :organisations do
    resources :products
    resources :memberships
    resources :users
    resources :roles
  end

  get 'accept_invitation/:invitation_code', to: "memberships#activate", as: "accept_invitation"

end

app/models/membership.rb
class Membership < ActiveRecord::Base
  # http://stackoverflow.com/questions/16771503/how-to-join-mutli-role-multi-organisation-tables-in-rails
  belongs_to :user
  belongs_to :organisation
  belongs_to :role

  before_create do
    self.invitation_code = SecureRandom.base64(12)
    self.role = self.organisation.roles.find_by_name("member")
  end

  def invitation_expired_at
    created_at + 10.days
  end

  def invitation_expired?
    invitation_expired_at < Time.now
  end

  def activate!
    if !activated?
      self.activated_at = Time.now
      save
    else
      raise "You have already activated your membership"
    end
  end

  def activated?
    !!activated_at
  end

end

app/controllers/memberships_controller.rb
class MembershipsController < ApplicationController
  before_action :find_organisation, except: [:activate]
  before_action :set_membership, only: [:show, :edit, :update, :destroy]

  # GET /memberships
  # GET /memberships.json
  def index
    @memberships = @organisation.memberships.all
  end

  # GET /memberships/1
  # GET /memberships/1.json
  def show
  end

  # GET /memberships/new
  def new
    @membership = @organisation.memberships.new
  end

  # GET /memberships/1/edit
  def edit
  end

  # POST /memberships
  # POST /memberships.json
  def create
    @membership = @organisation.memberships.new(membership_params)

    respond_to do |format|
      if @membership.save
        InvitationMailer.invitation_email(@membership).deliver_now
        format.html { redirect_to [@organisation, @membership], notice: 'Membership was successfully created.' }
        format.json { render :show, status: :created, location: @membership }
      else
        format.html { render :new }
        format.json { render json: @membership.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /memberships/1
  # PATCH/PUT /memberships/1.json
  def update
    respond_to do |format|
      if @membership.update(membership_params)
        format.html { redirect_to [@organisation, @membership], notice: 'Membership was successfully updated.' }
        format.json { render :show, status: :ok, location: @membership }
      else
        format.html { render :edit }
        format.json { render json: @membership.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /memberships/1
  # DELETE /memberships/1.json
  def destroy
    @membership.destroy
    respond_to do |format|
      format.html { redirect_to memberships_url, notice: 'Membership was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  def activate
    @membership = Membership.where(invitation_code: params[:invitation_code]).first
    if @membership.activated?
      flash[:error] = "no you cant do this"
      redirect_to "/"
    else
      @membership.activate!
      flash[:success] = "Now you are member of #{@membership.organisation}"
      redirect_to organisation_path(@membership.organisation)
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.

    def find_organisation
      @organisation = Organisation.find(params[:organisation_id])
    end

    def set_membership
      @membership = @organisation.memberships.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def membership_params
      params.require(:membership).permit(:email, :role_id)
    end

end

app/helpers/memberships_helper.rb
module MembershipsHelper
end

app/views/memberships/edit.html.erb
<h1>Editing Membership for <%= @membership.user.email %> of <%= @organisation.name %> </h1>


<%= simple_form_for([@organisation, @membership]) do |f| %>
    <% if @membership.errors.any? %>
        <div id="error_explanation">
          <h2><%= pluralize(@membership.errors.count, "error") %> prohibited this membership from being saved:</h2>

          <ul>
            <% @membership.errors.full_messages.each do |message| %>
                <li><%= message %></li>
            <% end %>
          </ul>
        </div>
    <% end %>


    <div class="form-group">

      <%= f.association :role, collection: @organisation.roles, include_blank: false %>

      <%= error_span(@membership[:email]) %>
    </div>

    <div class="actions">
      <%= f.submit %>
    </div>
<% end %>



<%= link_to 'Show', organisation_membership_path(@organisation, @membership) %>
<%= link_to 'Back', organisation_memberships_path(@organisation) %>

app/views/memberships/index.html.erb
<div class="page-header">
  <h1>Listing Members of <%= @organisation.name %> </h1>
</div>

<table class="table table-striped">
  <thead>
  <tr>
    <th> <%= Membership.human_attribute_name(:email) %></th>
    <th> <%= Membership.human_attribute_name(:organisation_id) %></th>
    <th> <%= Membership.human_attribute_name(:role) %></th>
    <th colspan="2"> Actions </th>
  </tr>
  </thead>

  <tbody>
  <% @memberships.each do |membership| %>
      <tr>
        <td><%= membership.user.email %></td>
        <td><%= membership.organisation.name %></td>
        <td><%= membership.role %></td>
        <td><%= link_to 'Show', organisation_membership_path(@organisation, membership) %></td>
        <td><%= link_to 'Edit', edit_organisation_membership_path(@organisation, membership) %></td>
      </tr>
  <% end %>
  </tbody>
</table>

app/views/memberships/new.html.erb
<h1>New Membership</h1>

<%= form_for([@organisation, @membership]) do |f| %>
    <% if @membership.errors.any? %>
        <div id="error_explanation">
          <h2><%= pluralize(@membership.errors.count, "error") %> prohibited this membership from being saved:</h2>

          <ul>
            <% @membership.errors.full_messages.each do |message| %>
                <li><%= message %></li>
            <% end %>
          </ul>
        </div>
    <% end %>


    <div class="form-group">
      <%= f.label :email, :class => 'control-label' %>
      <%= f.email_field :email, :class => 'form-control' %>
      <%= error_span(@membership[:email]) %>
    </div>

    <div class="actions">
      <%= f.submit %>
    </div>
<% end %>


<%= link_to 'Back', organisation_memberships_path(@organisation) %>

app/views/memberships/show.html.erb
<div class="page-header">
  <h1>Member details</h1>
</div>

<ul>
  <li><%= @membership.user.email %></li>
  <li><%= @membership.organisation.name %></li>
  <li><%= @membership.role %></li>
</ul>

<%= link_to 'Edit', edit_organisation_membership_path(@organisation, @membership), :class => 'btn btn-default' %>
<%= link_to 'Back', organisation_memberships_path(@organisation), :class => 'btn btn-default' %>