config/routes.rb
Rails.application.routes.draw do

  devise_for :users
  resources :product_categories

  resources :products

  root to: "products#index"

  resources :organisations do
    resources :products
    resources :memberships
    resources :users
    resources :roles
  end

  get 'accept_invitation/:invitation_code', to: "memberships#activate", as: "accept_invitation"

end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  #http://stackoverflow.com/questions/16771503/how-to-join-mutli-role-multi-organisation-tables-in-rails
  has_many :memberships
  has_many :organisations, through: :memberships
  has_one :roles_user
  has_one :role, through: :roles_user
  #belongs_to :organisation
  accepts_nested_attributes_for :organisations
  accepts_nested_attributes_for :role


  #enum role: {account_owner: 0, warehouse: 1, admin: 2}

  #TO_ASK
  # after_initialize :set_default_role, :if => :new_record?

  #TO_UPDATE
  # def set_default_role
  #   self.role ||= :account_owner
  # end


end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :find_organisation
  before_action :set_user, only: [:show, :edit, :update, :destroy]
  before_filter :authenticate_user!

  def index
    @users = User.all
  end

  def show
  end

  def edit
  end

  def update
    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to organisation_user_path(@organisation, @user), notice: 'User was successfully updated.' }
        format.json { render :show, status: :ok, location: @user }
      else
        format.html { render :edit }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @user.destroy
    respond_to do |format|
      format.html { redirect_to organisation_users_url, notice: 'User was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
  # Use callbacks to share common setup or constraints between actions.

  def find_organisation
    @organisation = Organisation.find(params[:organisation_id])
  end

  def set_user
    @user = @organisation.users.find(params[:id])
  end

  # Never trust parameters from the scary internet, only allow the white list through.
  #TO_ASK how to add product_category_attributes to permitted attributes below?
  def user_params
    params.require(:user).permit(:email, :organisation_id,
                                 :roles_user_attributes =>:role_id)
  end

end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/destroy.html.erb
<h1>Users#destroy</h1>
<p>Find me in app/views/users/destroy.html.erb</p>

app/views/users/edit.html.erb
<h1>Users#edit</h1>
<p>Find me in app/views/users/edit.html.erb</p>

app/views/users/index.html.erb
<div class="page-header">
<h1>Listing Users</h1>
  </div>

<table class="table table-striped">
  <thead>
  <tr>
    <th> <%= User.human_attribute_name(:email) %></th>
    <th> <%= User.human_attribute_name(:organisation_id) %></th>
    <th> <%= User.human_attribute_name(:role) %></th>
    <th colspan="3"> Actions </th>
  </tr>
  </thead>

  <tbody>
  <% @users.each do |user| %>
      <tr>
        <td><%= user.email %></td>
        <td><%= user.organisations.first.name %></td>
        <td><%= user.memberships.first.role %></td>
        <td><%= link_to 'Show', organisation_user_path(@organisation, user) %></td>
        <td><%= link_to 'Edit', edit_organisation_user_path(@organisation, user) %></td>
        <td><%= link_to 'Destroy', [@organisation, user], method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
  <% end %>
  </tbody>
</table>

app/views/users/show.html.erb
<div class="page-header">
  <h1>User details</h1>
</div>

<ul>
  <li><%= @user.email %></li>
  <li><%= @user.organisations.first.name %></li>
  <li><%= @user.role.name %></li>
</ul>

<%= button_to 'Back', organisation_users_path, :method => :get, :class => 'btn btn-default' %>

app/views/users/update.html.erb
<h1>Users#update</h1>
<p>Find me in app/views/users/update.html.erb</p>