config/routes.rb
Rails.application.routes.draw do

  devise_for :users
  resources :product_categories

  resources :products

  root to: "products#index"

  resources :organisations do
    resources :products
    resources :memberships
    resources :users
    resources :roles
  end

  get 'accept_invitation/:invitation_code', to: "memberships#activate", as: "accept_invitation"

end

app/models/role.rb
class Role < ActiveRecord::Base
  after_create :create_default_entity_permissions

  belongs_to :organisation
  has_many :entity_permissions
  has_many :memberships

  def to_s
    name
  end

  private

  def create_default_entity_permissions
    ["Product", "User"].each do |entity_name|
      self.entity_permissions.create(entity: entity_name, c: true, r: true, u: true, d: true)
    end
  end

end

app/controllers/roles_controller.rb
class RolesController < ApplicationController
  before_action :find_organisation
  before_action :set_role, only: [:show, :edit, :update, :destroy]

  # GET /roles
  # GET /roles.json
  def index
    @roles = @organisation.roles.all
  end

  # GET /roles/1
  # GET /roles/1.json
  def show
  end

  # GET /roles/new
  def new
    @role = @organisation.roles.new
  end

  # GET /roles/1/edit
  def edit
  end

  # POST /roles
  # POST /roles.json
  def create
    @role = @organisation.roles.new(role_params)

    respond_to do |format|
      if @role.save
        format.html { redirect_to [@organisation, @role], notice: 'Role was successfully created.' }
        format.json { render :show, status: :created, location: @role }
      else
        format.html { render :new }
        format.json { render json: @role.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /roles/1
  # PATCH/PUT /roles/1.json
  def update
    respond_to do |format|
      if @role.update(role_params)
        format.html { redirect_to [@organisation, @role], notice: 'Role was successfully updated.' }
        format.json { render :show, status: :ok, location: @role }
      else
        format.html { render :edit }
        format.json { render json: @role.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /roles/1
  # DELETE /roles/1.json
  def destroy
    @role.destroy
    respond_to do |format|
      format.html { redirect_to roles_url, notice: 'Role was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private

  def find_organisation
    @organisation = Organisation.find(params[:organisation_id])
  end

  # Use callbacks to share common setup or constraints between actions.
    def set_role
      @role = @organisation.roles.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def role_params
      params.require(:role).permit(:organisation_id, :name)
    end
end

app/helpers/roles_helper.rb
module RolesHelper
end

app/views/roles/_form.html.erb
<%= form_for([@organisation, @role]) do |f| %>
  <% if @role.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@role.errors.count, "error") %> prohibited this role from being saved:</h2>

      <ul>
      <% @role.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :organisation %><br>
    <%= @organisation.name %>
  </div>
  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/roles/edit.html.erb
<h1>Editing Role</h1>

<%= render 'form' %>

<%= link_to 'Show', [@organisation, @role] %> |
<%= link_to 'Back', organisation_roles_path(@organisation) %>

app/views/roles/index.html.erb
<p id="notice"><%= notice %></p>

<div class="page-header">
  <h1>Listing Roles of <%= @organisation.name %> </h1>
</div>

<table class="table table-striped">
  <thead>
    <tr>
      <th>Organisation</th>
      <th>Role</th>
      <th colspan="3">Actions</th>
    </tr>
  </thead>

  <tbody>
    <% @roles.each do |role| %>
      <tr>
        <td><%= role.organisation %></td>
        <td><%= role.name %></td>
        <td><%= link_to 'Show', organisation_role_path(@organisation, role) %></td>
        <td><%= link_to 'Edit', edit_organisation_role_path(@organisation, role) %></td>
        <td><%= link_to 'Destroy', [@organisation, role], method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Role', new_organisation_role_path(@organisation) %>

app/views/roles/new.html.erb
<h1>New Role</h1>

<%= render 'form' %>

<%= link_to 'Back', organisation_roles_path(@organisation) %>

app/views/roles/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Organisation:</strong>
  <%= @role.organisation %>
</p>

<p>
  <strong>Role:</strong>
  <%= @role.name %>
</p>

<%= link_to 'Edit', edit_organisation_role_path(@organisation, @role) %>
<%= link_to 'Back', organisation_roles_path(@organisation) %>